<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

<!-- 
    <xacro:macro name="example_macro" params="a b c">
        <link name="dummy_link">
            <visual>
                <geometry>
                    <box size="${a} ${b} ${c}" />
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <xacro:example_macro a="2" b="3" c="4"/> -->


    <!-- <material name="blue">
        <color rgba="0 0 0.5 1"/>
    </material>

    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material> -->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/> 
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/> 
            <material name="blue"/>
        </visual>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="0.05"/>
                </geometry>
                <origin xyz="0 0 0 " rpy="${pi / 2.0} 0 0" />
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <!-- <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.05"/>
            </geometry>
            <origin xyz="0 0 0 " rpy="${pi / 2.0} 0 0" />
            <material name="gray" />
        </visual>
    </link> -->

    <!-- <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <material name="gray" />
        </visual>
    </link> -->

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0.2 0 -0.025" rpy="1.57 0 0" />
            <material name="gray" />
        </visual>
    </link>

    <!-- [[[joint section]]] -->

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width +  wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-0.15 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 0" />
    </joint>


</robot>